<?php
require_once '../includes/admin_auth.php';
admin_require_login(true);
include '../includes/header.php';
include '../includes/db.php';
require_once '../includes/capstone2_features.php';
ve_ensure_capstone2_schema($conn);
$rows = mysqli_query($conn, "SELECT bs.booking_id, gi.guest_name, gi.mobile, bs.check_in_date, bs.check_out_date, bs.guests, bs.time_type, bs.status, bs.archived_at FROM bookings bs INNER JOIN guests gi ON gi.guest_id = bs.guest_id WHERE COALESCE(bs.archived,0)=1 ORDER BY bs.archived_at DESC, bs.booking_id DESC");
function arStay($type){ return $type === 'day' ? 'Day Tour' : ($type === 'overnight' ? 'Overnight Stay' : ($type === '22hour' ? '22-Hour Stay' : ucfirst($type))); }
?>
<div id="sidebar" class="sidebar"><a href="../index.php" class="sidebar-title sidebar-brand-link">Villa Eusebio</a><a href="admin-panel.php" class="nav-link"><span class="nav-icon">D</span><span>Dashboard</span></a><a href="reservation.php" class="nav-link"><span class="nav-icon">R</span><span>Reservation</span></a><a href="sales.php" class="nav-link"><span class="nav-icon">S</span><span>Sales Record</span></a><a href="announcements.php" class="nav-link"><span class="nav-icon">A</span><span>Announcement</span></a><a href="subscribers.php" class="nav-link"><span class="nav-icon">EM</span><span>Subscribers</span></a><a href="archive.php" class="nav-link active"><span class="nav-icon">AR</span><span>Archive</span></a><a href="settings.php" class="nav-link"><span class="nav-icon">ST</span><span>Settings</span></a></div>
<div class="admin-dashboard"><div class="admin-topbar"><div class="admin-brand"><button id="menuToggle" class="menu-btn">Menu</button><div><h1>Villa Eusebio</h1><p>Reservation Archive</p></div></div><div class="admin-userbar"><strong>Owner</strong><a class="refresh-btn" href="archive.php">Back</a><a href="../api/logout.php" class="logout-btn">Logout</a></div></div>
<div class="main-content"><div class="admin-page-heading"><div><h2>Reservation Archive</h2><p class="reservation-helper-text">Archived reservation rows are stored here and can be restored.</p></div><a class="admin-export-btn" href="archive.php">Archive Menu</a></div><?php if(isset($_GET['success'])): ?><div class="admin-alert success-alert"><?php echo htmlspecialchars($_GET['success']); ?></div><?php endif; ?><div class="table-container"><table class="reservation-table"><thead><tr><th>ID</th><th>Guest</th><th>Phone</th><th>Check-in</th><th>Check-out</th><th>Guests</th><th>Type</th><th>Status</th><th>Archived</th><th>Action</th></tr></thead><tbody><?php if($rows): while($row=mysqli_fetch_assoc($rows)): ?><tr><td>#<?php echo (int)$row['booking_id']; ?></td><td><?php echo htmlspecialchars($row['guest_name']); ?></td><td><?php echo htmlspecialchars($row['mobile']); ?></td><td><?php echo htmlspecialchars(date('M d, Y', strtotime($row['check_in_date']))); ?></td><td><?php echo htmlspecialchars(date('M d, Y', strtotime($row['check_out_date']))); ?></td><td><?php echo (int)$row['guests']; ?></td><td><span class="stay-badge"><?php echo htmlspecialchars(arStay($row['time_type'])); ?></span></td><td><span class="status <?php echo htmlspecialchars($row['status']); ?>"><?php echo htmlspecialchars(ucfirst($row['status'])); ?></span></td><td><?php echo $row['archived_at'] ? htmlspecialchars(date('M d, Y h:i A', strtotime($row['archived_at']))) : 'N/A'; ?></td><td><form method="POST" action="../api/restore_booking.php"><input type="hidden" name="id" value="<?php echo (int)$row['booking_id']; ?>"><input type="hidden" name="redirect" value="archive_reservation"><button class="modal-btn btn-approve" type="submit">Restore</button></form></td></tr><?php endwhile; endif; ?></tbody></table></div></div></div>
<script>document.addEventListener('DOMContentLoaded',function(){const btn=document.getElementById('menuToggle'),sidebar=document.getElementById('sidebar'),dash=document.querySelector('.admin-dashboard');if(localStorage.getItem('sidebar')==='collapsed'){sidebar.classList.add('active');dash.classList.add('shift');}if(btn){btn.onclick=function(){sidebar.classList.toggle('active');dash.classList.toggle('shift');localStorage.setItem('sidebar',sidebar.classList.contains('active')?'collapsed':'expanded');};}});</script>



