<?php
require_once '../includes/admin_auth.php';
admin_require_login(true);
include '../includes/header.php';
include '../includes/db.php';
require_once '../includes/capstone2_features.php';
ve_ensure_capstone2_schema($conn);
$rows = mysqli_query($conn, "SELECT image_id, image_path, caption, description, archived_at FROM gallery_images WHERE archived_at IS NOT NULL ORDER BY archived_at DESC, image_id DESC");
?>
<div id="sidebar" class="sidebar"><a href="../index.php" class="sidebar-title sidebar-brand-link">Villa Eusebio</a><a href="admin-panel.php" class="nav-link"><span class="nav-icon">D</span><span>Dashboard</span></a><a href="reservation.php" class="nav-link"><span class="nav-icon">R</span><span>Reservation</span></a><a href="sales.php" class="nav-link"><span class="nav-icon">S</span><span>Sales Record</span></a><a href="announcements.php" class="nav-link"><span class="nav-icon">A</span><span>Announcement</span></a><a href="subscribers.php" class="nav-link"><span class="nav-icon">EM</span><span>Subscribers</span></a><a href="archive.php" class="nav-link active"><span class="nav-icon">AR</span><span>Archive</span></a><a href="settings.php" class="nav-link"><span class="nav-icon">ST</span><span>Settings</span></a></div>
<div class="admin-dashboard"><div class="admin-topbar"><div class="admin-brand"><button id="menuToggle" class="menu-btn">Menu</button><div><h1>Villa Eusebio</h1><p>Settings Archive</p></div></div><div class="admin-userbar"><strong>Owner</strong><a class="refresh-btn" href="archive.php">Back</a><a href="../api/logout.php" class="logout-btn">Logout</a></div></div>
<div class="main-content"><div class="admin-page-heading"><div><h2>Settings / Gallery Archive</h2><p class="reservation-helper-text">Archived gallery images are stored here.</p></div><a class="admin-export-btn" href="archive.php">Archive Menu</a></div><?php if(isset($_GET['success'])): ?><div class="admin-alert success-alert"><?php echo htmlspecialchars($_GET['success']); ?></div><?php endif; ?><div class="gallery-admin-list"><?php if($rows && mysqli_num_rows($rows)>0): while($row=mysqli_fetch_assoc($rows)): ?><div class="gallery-admin-item"><img src="../<?php echo htmlspecialchars($row['image_path']); ?>" alt=""><p><?php echo htmlspecialchars($row['caption'] ?: 'Villa Eusebio'); ?></p><?php if($row['description']): ?><small class="gallery-admin-desc"><?php echo htmlspecialchars($row['description']); ?></small><?php endif; ?><small class="home-gallery-flag">Archived <?php echo htmlspecialchars(date('M d, Y', strtotime($row['archived_at']))); ?></small><form method="POST" action="../api/restore_gallery_image.php"><input type="hidden" name="image_id" value="<?php echo (int)$row['image_id']; ?>"><button class="modal-btn btn-approve" type="submit">Restore</button></form></div><?php endwhile; else: ?><p class="muted-text">No archived gallery images.</p><?php endif; ?></div></div></div>
<script>document.addEventListener('DOMContentLoaded',function(){const btn=document.getElementById('menuToggle'),sidebar=document.getElementById('sidebar'),dash=document.querySelector('.admin-dashboard');if(localStorage.getItem('sidebar')==='collapsed'){sidebar.classList.add('active');dash.classList.add('shift');}if(btn){btn.onclick=function(){sidebar.classList.toggle('active');dash.classList.toggle('shift');localStorage.setItem('sidebar',sidebar.classList.contains('active')?'collapsed':'expanded');};}});</script>



